version: '3'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./data:/data
      - ./figures:/figures
      - ./models:/models
      - ./src:/app

